/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class number_MathUtils */

#ifndef _Included_number_MathUtils
#define _Included_number_MathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     number_MathUtils
 * Method:    isPrime
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_number_MathUtils_isPrime
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
